env: "mamujoco"

env_args:
  env_args:
    scenario: HalfCheetah-v2
    agent_conf: "6x1"
    agent_obsk: 0
    episode_limit: 100

run: "run_mamujoco"
task: -1

local_results_path: "results/"

test_greedy: True
test_nepisode: 10

test_interval: 10000
log_interval: 10000
runner_log_interval: 10000
learner_log_interval: 10000

t_max: 1000000